export type TScreen =
    | "carSelection"
    | "serviceNeeds"
    | "maintenanceDetails"
    | "serviceSelection"
    | "packageSelection"
    | "describeMore"
    | "opsCode"
    | "consultantSelection"
    | "appointmentTiming"
    | "appointmentSelection"
    | "transportationNeeds"
    | "appointmentConfirmation"