export type TScreen =
    | "carSelection"
    | "serviceNeeds"
    | "maintenanceDetails"
    | "serviceSelection"
    | "packageSelection"
    | "describeMore"
    | "opsCode"
    | "consultantSelection"
    | "appointmentTiming"
    | "appointmentSelection"
    | "transportationNeeds"
    | "appointmentConfirmation"
    | "appointmentConfirmed"
    | "location"
    | "payment"
    | "serviceOfferProductPage"
    | "manageAppointment"

export type TMobileScreen =
    | "carSelection"
    | "serviceNeeds"
    | "maintenanceDetails"
    | "serviceSelection"
    | "packageSelection"
    | "describeMore"
    | "opsCode"
    | "appointmentTiming"
    | "appointmentSelection"
    | "appointmentConfirmation"
    | "appointmentConfirmed"
    | "location"
    | "payment"
    | "serviceOfferProductPage"

